### ISSUE TITLE
Error: could not find environment: cmd.exe

### ISSUE THREAD

**Issue by joaobarcia** [darkdreamingdan/PSCondaEnvs#1]
Hi @darkdreamingdan , thanks for the work.

I ran `conda install -n root -c pscondaenvs pscondaenvs` in the powershell and got a success message by the end of the installation process.

However, if I try to run activate, I get:
```
Error: could not find environment: cmd.exe
Environment not changed.
```

If I try to run `conda install -n root -c pscondaenvs pscondaenvs` again, or inside CMD I now get:
```
Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/win-64/
```

Any ideas? Happy to send any info that might help with debugging. On Windows 10 64bits.

**Comment by darkdreamingdan** [comment]
What happens if you execute the following in cmd or powershell:

`conda.exe "..checkenv" "cmd.exe" "env_name"`
Try with a valid env name and an invalid one.

You may need to simply update your version of conda:
`conda update conda`

Also, in Powershell, can you give me the output of the following:
`Get-Command conda`

**Comment by darkdreamingdan** [comment]
Inspecting things in detail - I believe that's it.  You need to update Conda to 4.1 or above.  

Please upgrade and check if it works.  Thanks for the report - if I'm correct, I'll update the package with a fixed requirement.

**Comment by joaobarcia** [comment]
Ah, definitely! It seems my Conda version was quite old (3.2.0a1). I couldn't even update it due to this issue https://github.com/conda/conda/issues/3323 . 

Anyway, uninstalled everything, re-installed to Anaconda 4.4.0, re-installed pscondaenvs and it's working great now :) Thanks!

**Comment by darkdreamingdan** [comment]
Great news! Applied a fixed reqiurement in https://github.com/darkdreamingdan/PSCondaEnvs/commit/2f6ca1af6261555ba5774c0d3f6c122e28984d6e

Cheers
